### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by michalceb** [iDebugAll/phonebox_plugin#12]
Netbox version: 3.0.4
Phonebox_plugin version: 0.0.2-beta.1

Plugin is displaying correctly, however, when I am trying to use filters - looking up numbers for a specific Customer or Region, it is not taking effect. Just displays list of all numbers.

Any suggestions if I am possibly doing something wrong, or is it a bug?

**Comment by iDebugAll** [comment]
Hi @michalceb. Thank you for your report. I was able to reproduce this behaviour. Filter by Region, Tenant, and Provider does not work for NetBox 3.X through both GUI and REST API. General Search and filter by Tags works as expected at the same time. It looks like a bug.
