### ISSUE TITLE
Add support for NAT-like translations

### ISSUE THREAD

**Issue by collinmoerman** [iDebugAll/phonebox_plugin#14]
Add support for a NAT-like mechanism to map a PSTN accessible number to an internal PBX number.

Great work on this plugin so far!

**Comment by iDebugAll** [comment]
Hi @collinmoerman. 
This can already be modelled in the plugin by setting `forward_to` pointing to an internal number for a PSTN number.
For example:
- Internal number 1000 in tenant PBX.
- External number +12345678900 in tenant PSTN with forward_to set to 1000.

This relation will represent number +12345678900 being mapped to 1000.

Number and/or SIP manipulations are good idea too. But it is quite not straightforward task to generalise and represent them as a vendor independent model.
