### ISSUE TITLE
[Documentation] wrong install command

### ISSUE THREAD

**Issue by sgofferj** [iDebugAll/phonebox_plugin#25]
In the readme the install command is
```bash
pip3 install phonebox_plugin
```
Correct is
```bash
pip3 install phonebox-plugin
```

**Comment by iDebugAll** [comment]
Thanks, fixed.
Both options will actually work (`pip install` command replaces underscores with dashes in the package name).
The package is named `phonebox-plugin` on PyPI as per PEP8.
