### ISSUE TITLE
unable to install on NetBox v 3.4.5

### ISSUE THREAD

**Issue by Harrball76** [iDebugAll/phonebox_plugin#29]
every time I try to install is crashes netbox. is there anyway to get working??

Thanks for the help

**Comment by asolupe** [comment]
I've the same issue and would like to implement in 3.4.5 version

**Comment by iDebugAll** [comment]
Latest PhoneBox plugin version 0.0.5-beta.1 is now compatible with NetBox 3.2-3.4.
