### ISSUE TITLE
Tags not visible in list view

### ISSUE THREAD

**Issue by flohoff** [iDebugAll/phonebox_plugin#40]
Hi,
as there is no lifecycle field e.g. Active/Planned/Staged etc i was trying to use tags. The issue with tags is that they are not visible in list view.

So at least make the tags visible in list view, even better would be the netbox default list editor where every user can choose itself what columns they like to see.

Flo

**Comment by iDebugAll** [comment]
Hi @flohoff, I've just published a new plugin version. #44 improves the tags handling and adds this column in the list view for Numbers and Voice Circuits. Plugin template still needs some refactoring to inherit new NetBox layout but it works.
