### ISSUE TITLE
Issue with adding tenant after installing plugin on Netbox 3.7.1

### ISSUE THREAD

**Issue by dponzone** [iDebugAll/phonebox_plugin#45]
Just upgraded my Netbox to 3.7.1 and I installed latest plugin (0.0.7b2).
Install was fine, but afterwards, when I tried to add a tenant in Netbox (my Netbox DB is almost empty), I had the following error:

<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'number_list' not found. 'number_list' is not a valid view function or pattern name.

Python version: 3.9.2
NetBox version: 3.7.1
Plugins: 
  phonebox_plugin: v0.0.7-beta.2

David

**Comment by InsaneSplash** [comment]
We have seen the same issue. Disabling the plugin allows you to access the newly created tenant.

**Comment by InsaneSplash** [comment]
```
<class 'django.urls.exceptions.NoReverseMatch'>

Reverse for 'number_list' not found. 'number_list' is not a valid view function or pattern name.

Python version: 3.9.18
NetBox version: 3.7.2
Plugins: 
  phonebox_plugin: v0.0.7-beta.2
```

**Comment by InsaneSplash** [comment]
@dponzone I think this project might be stale these days.

**Comment by dponzone** [comment]
It seems, a pity.

**Comment by iDebugAll** [comment]
I’ve just published a new plugin release. It’s now compatible with NB 3.7 and 4.0.

**Comment by dponzone** [comment]
Ah nice, works fine, thanks!
