### ISSUE TITLE
migrations won't be applied...

### ISSUE THREAD

**Issue by adrianhiller** [iDebugAll/phonebox_plugin#48]
No migrations to apply.
  Your models in app(s): 'phonebox_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

Netbox Version: 3.7.5
Python Version: 3.11.2

**Comment by iDebugAll** [comment]
I’ve just published a new plugin release. It’s now compatible with NB 3.7 and 4.0.
