### ISSUE TITLE
Doesnt install in a fresh copy of netbox 4.0.2

### ISSUE THREAD

**Issue by mcarasso-sts** [iDebugAll/phonebox_plugin#49]
When going trying to install this plugin I was getting an error when running collect Static that it failed due to no module 'extra.plugins'. It appears 3.7 migrated to 'netbox.plugins'

**Comment by iDebugAll** [comment]
I’ve just published a new plugin release. It’s now compatible with NB 3.7 and 4.0.

**Comment by mcarasso-sts** [comment]
You are a gentlemen and a scholar works like a charm in 4.0.2
